services:
  bloglist-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://bloglist-backend-prod:3003/api
    container_name: bloglist-frontend-prod
    networks:
      - bloglist-app-network

  bloglist-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bloglist-backend-prod
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://bloglist:ds76gj2jdrk@bloglist.h7vm4.mongodb.net/?retryWrites=true&w=majority&appName=bloglist
      - SECRET=mysecret007
      - PORT=3003
    ports:
      - "3003:3003"
    networks:
      - bloglist-app-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: bloglist-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    networks:
      - bloglist-app-network

  nginx:
    image: nginx:1.20.1
    container_name: reverse-proxy
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - bloglist-frontend
      - bloglist-backend
    networks:
      - bloglist-app-network

volumes:
  mongo_data:
  bloglist-frontend-build:

networks:
  bloglist-app-network:
